import pygame
#SCREEN CONSTANTS
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

#ASTEROID CONSTANTS
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

#PLAYER CONSTANTS
PLAYER_RADIUS = 20
SCREEN = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
PLAYER_TURN_SPEED = 280
PLAYER_SPEED = 200
PLAYER_SHOOT_COOLDOWN = 0.3 #seconds

#SHOT CONSTANTS
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
TURRET_SHOOT_SPEED = 590
SNIPER_TURRET_SHOOT_SPEED = 1000
SHOTGUN_TURRET_SHOOT_SPEED = 430

#TURRET CONSTANTS
TURRET_RADIUS = 15
NORM_TURRET_SHOT_COOLDOWN = 0.9
SHOTGUN_TURRET_SHOT_COOLDOWN = 1.9
SNIPER_TURRET_SHOT_COOLDOWN = 2.9
MACHINE_GUN_SHOT_COOLDOWN = 0.45
MACHINE_GUN_MIN_COOLDOWN = 0.07
MACHINE_GUN_BURST_SIZE = 30
MACHINE_GUN_RELOAD = 3

